# Generated by Django 5.2.4 on 2025-10-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
    ]
