# Generated by Django 5.2.6 on 2025-11-04 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
    ]
