# Generated by Django 5.2.6 on 2025-11-04 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Автор урока'),
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='taught_modules', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели модуля'),
        ),
    ]
