# Generated by Django 5.2.6 on 2025-11-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_author_module_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/', verbose_name='Изображение (JPG, PNG)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/', verbose_name='PDF-файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/', verbose_name='Видео-файл (MP4, AVI)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео (Youtube/Vimeo)'),
        ),
    ]
