# Generated by Django 5.2.6 on 2025-11-04 07:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lesson_image_file_lesson_pdf_file_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Проходной балл (в %)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант А'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант Б'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант В'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант Г'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('exact', 'Точь-в-точь (текстовый ответ)'), ('choice', 'Выбор из вариантов')], default='exact', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(max_length=255, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='max_score',
            field=models.PositiveIntegerField(default=1, verbose_name='Балл за ответ'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='score',
            field=models.FloatField(default=0, verbose_name='Балл (%)'),
        ),
    ]
