# Generated by Django 5.2.6 on 2025-11-07 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_test_passing_score_testquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
