# Generated by Django 5.2.6 on 2025-11-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testquestion_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'verbose_name': 'Попытка теста', 'verbose_name_plural': 'Попытки тестов'},
        ),
        migrations.AddField(
            model_name='testanswer',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл за ответ'),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('graded', 'Проверено')], default='pending', max_length=10, verbose_name='Статус проверки'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='Ответ студента'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testsubmission', verbose_name='Попытка теста'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Правильный ответ (для 'Выбора из вариантов')"),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='max_score',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. балл за этот вопрос'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор из вариантов'), ('open_ended', 'Развернутый ответ (проверяется учителем)')], default='choice', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='score',
            field=models.FloatField(default=0, verbose_name='Итоговый балл (%)'),
        ),
    ]
