# Generated by Django 5.2.6 on 2025-11-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_testsubmission_options_testanswer_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(blank=True, verbose_name='Иконка (SVG код)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Особенность курса',
                'verbose_name_plural': 'Особенности курса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
                ('description', models.CharField(max_length=255, verbose_name="Описание (напр. 'д.ф.н., профессор')")),
                ('photo', models.ImageField(upload_to='teacher_cards/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_cards', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Карточка преподавателя (на главной)',
                'verbose_name_plural': 'Карточки преподавателей (на главной)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
