# Generated by Django 5.0.4 on 2025-11-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coursefeature_teachercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант Д'),
        ),
    ]
