# Generated by Django 5.0.4 on 2025-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testquestion_option_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='goal_lesson',
            field=models.TextField(blank=True, null=True, verbose_name='Цель занятия'),
        ),
    ]
